spring.application.name=Research.Paper.Management.API
# Server
server.port=8080

# H2 database
spring.datasource.url=jdbc:h2:mem:researchdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Logging
logging.level.org.springframework.security=INFO